#!/usr/bin/env bash

print_style () {
    if [ "$2" == "info" ] ; then
        COLOR="96m"
    elif [ "$2" == "success" ] ; then
        COLOR="92m"
    elif [ "$2" == "warning" ] ; then
        COLOR="93m"
    elif [ "$2" == "danger" ] ; then
        COLOR="91m"
    else #default color
        COLOR="0m"
    fi

    STARTCOLOR="\e[$COLOR"
    ENDCOLOR="\e[0m"

    printf "$STARTCOLOR%b$ENDCOLOR" "$1"
}

display_options () {
    printf "Available options:\n";
    print_style "   go api (alias ga)" "info"; printf "\t Enter workspace with laradock user and moved to api\n"
}

go_to () {
    cc="${dcm} -w ${cws}/$1 ${ctn} bash"
    print_style "Run: ${cc}\n" "info"
    ${cc}
}

cws="/var/www"
ctn="elic-zero-workspace-1"
dcm="docker exec -it -u laradock"

case $1 in
    go)
        case $2 in
            api)
                go_to "elic-zero-api"
                ;;
        esac
        ;;
    ga)
        go_to "elic-zero-api"
        ;;
    ngrok)
        show_ngrok
        ;;
    *)
        display_options
        ;;
esac
